### ISSUE TITLE
Make sure archive db dumps are complete

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#10308]
We want to make sure that there are no missing blocks in the archive databases that are dumped to Google Cloud.

Those dumps are taken from the mainnet "3" database. The URL is https://console.cloud.google.com/storage/browser/mina-archive-dumps;tab=objects?forceOnBucketsSortingFiltering=false&authuser=1&project=o1labs-192920&prefix=&forceOnObjectsSortingFiltering=false

(1) There's an existing script `download-missing-blocks.sh` for the Rosetta nodes that came be adapted for this purpose.

(2) Besides missing blocks, we want to be sure that the nonces in the db `balances` table are complete. We can run the replayer on the db for that purpose with the `--set-nonces` flag. This will discover any balance and ledger hash errors in the database.

The replayer currently dumps a checkpoint file after each run (if no target hash is given), so it only need run from the last checkpoint forward.

After both of those steps are taken, there's good assurance the db is complete and accurate.

[Steven P.]: Adding some steps below to track work to complete this item. 

- [x] Deploy new archive DB to Mainnet with enough resources to run the replayer. 
- [x] Validate integration with cloudSQL postgres
- [x] Performance benchmark cloudSQL postgres implementation
- [x] Update `download-missing-blocks.sh` script as needed to validate block completeness. 
- [x] Run replayer to validate block integrity. 
- [x] Automate the prior 3 steps to generate a recurring report.

**Comment by psteckler** [comment]
An issue to consider is having enough shared memory for Postgresql. Running the replayer on mainnet `3` db results in the out-of-shared-memory errors.

The Rosetta 1 db on mainnet has a Postgresql config that accomodates the replayer.

**Comment by stevenplatt** [comment]
The work of this Epic is now completed. Individual Zenhub issues have been linked to this epic to document more specific details for each item. High level documentation for all part of this work have been documented as a `README` within the `mina-deployments` repository and can be found [HERE](https://github.com/MinaProtocol/mina-deployments/tree/main/src/mainnet/archive_service). A final item that was not included with this work, is to generate an automated report for the results of the integrity checks. This item has been marked as a future "To-Do" within the readme documentation, but has not been assigned a specific delivery date.
