### ISSUE TITLE
Ensure good test coverage of new code in develop

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#11768]
We want to ensure that we have a good test coverage for the code that has not yet been deployed on the mainnet.

We will want to

- [ ] look at where in the codebase the most (meaningful) changes are
- [ ] run the tests, and look at the coverage report
- [ ] understand which part of the actual functionality is well tested already
- [ ] potentially write new tests to fill any gaps.
