### ISSUE TITLE
verification benchmarks

### ISSUE THREAD

**Issue by fabrizio-m** [MinaProtocol/mina#12813]
Cover benchmark concerning the potentially excessive cost in batched verification highlighted in #12356.
- [x] benchmark batched verification time in kimchi.
- [ ] benchmark batched verification memory usage in kimchi.
- [ ] benchmark `Pickles.verify` memory usage.
- [ ] benchmark `Pickles.verify` time.
- [ ] benchmark kimchi verify core utilization.
