### ISSUE TITLE
Automate updating system-proofs dependency 

### ISSUE THREAD

**Issue by dkijania** [MinaProtocol/mina#14196]
## Context

Crypto team would like to automate updating system-proof dependency in mina repo. Currently this is manual process, which involves

- Given system-proofs repo is submodule of mina repo
- And corresponding branch in system-proofs relates to mina branch (For example: berkeley -> berkeley)
- When there is a push into system-proofs mainline branches (main/develop/compatible/berkeley)
- Then a PR in mina repo is created bumping commit of system-proofs
- And Buildkite pipeline is started. 

## Solution

In order to satisfy above need we can use branch autosync tool and enhance it with submodule support. The idea is to accept push from system-proofs repository and perform required operation. Flow is rather simple and we need to add only couple of things:

### TODO

- [ ] configure system proofs repo to send push event to our cloud function module. **Estimate - 0 days**
- [ ] enhance autosync tool to accept push from submodule, create new commit and create PR in mina repo. **Estimate - 3 days**
- [ ] add support to start buildkite pipeline. **Estimate - 2 days**
