### ISSUE TITLE
Clean Ci artifacts on daily basis

### ISSUE THREAD

**Issue by dkijania** [MinaProtocol/mina#14199]
Currently we have > 200 TB unused data in a from of:

- Logs
- Docker Images
- Deb packages

We need to implement some solution which will clean above locations with some grace period (for example 60 days from current time).

### TODO

- [ ] Implement google cloud function based on gist: https://gist.github.com/dkijania/e7fb84580435bbd7ea6924f45512d643
- [ ] Create cron job which will trigger above function on daily basis
- [ ] Setup our GCloud instance with necessary infra: https://cloud.google.com/scheduler/docs/tut-pub-sub
