### ISSUE TITLE
Overridable FFAdd (iteration 1)

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#14274]
In order to take the thinnest possible vertical slice, we ideally want to modify one of the existing gates to assert a different constraint.

All of the 'unconditional gates' are hard-coded because they are explicitly used by pickles, so we cannot override them. Instead, we'll need to use one of the optional gates. `ForeignFieldAdd` is a good candidate for this first pass, because it doesn't use lookups.

The work is then:
- [x] add a boolean to the prover and verifier indexes that tells us whether we're using the original gate (false) or the new gate (true) with the `ForeignFieldAdd` selector.
- [x] update the index creation function to accept this new boolean
- [x] propagate that boolean through the bindings to pickles (hard-coded as false)
- [x] update [the gate's inclusion in the linearization](https://github.com/o1-labs/proof-systems/blob/33fd70404c8ca997792b9af1202c7f54e33264ff/kimchi/src/linearization.rs#L94) to respect the boolean
- [x] update [the prover](https://github.com/o1-labs/proof-systems/blob/33fd70404c8ca997792b9af1202c7f54e33264ff/kimchi/src/prover.rs#L775) to respect the boolean
- [x] update pickles to pass that boolean through the system instead of hard-coding it
  - [x] probably best as an optional argument to compile, so that it won't affect the Mina circuits by default
  - [x] proving path 
  - [x] verification path... linking up to `Scalars_plus`
  - [x] tags & passing to sub-proofs
- [x] create a snarky circuit using the gate, check that it proves and verifies
- [x] use that circuit as a pickles circuit, set the boolean argument to true, debug and fix whatever needs fixing
  - [x] created test and set flag to false, no regressions
  - while doing this, ensure that the Mina circuits are unchanged and still work
  - [x] above is mina compile, etc?
- [ ] demo overriding FFAdd
