### ISSUE TITLE
Retire unused Snappnet testnet

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#14297]
# Summary
This task is to document the retiring of the `Snappnet` testnet. This original testnet was deployed in April 2021 along with the original `Mainnet` and was used to demonstrate smart contract functionality. This network is no longer in use and hase been replaced by the `Berkeley` testnet for developing smart contract applications.

## Tasks
This testnet no longer has working infrastructure deployment files. The following items need to be removed manually: 

- [x] Snappnet namespace: this will remove all namespace scoped systems, including mina nodes and storage volumes
- [x] Snappnet seed IP addresses: IP addresses are reserved for `seed` nodes within testnets, these are not tied to a namespace and must be manually removed. 
- [x] Snappnet DNS names: DNS names are configured for seed nodes in AWS as part of testnet deployment and must be manually removed. 
- [x] Snappnet seed list: The testnet seed list sits outside of kubernetes and does not get removed with the namespace. It must be manually removed.
