### ISSUE TITLE
 Integrate folding of one constraint with the IVC circuit

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#15686]
- [ ] o1-labs/proof-systems#2269 (Integration, Danny+Misha)
- [ ] https://github.com/o1-labs/proof-systems/pull/2279 (Blinders, Danny+Misha)
- [x] o1-labs/proof-systems#2233 (Danny)
- [x] o1-labs/proof-systems#2247 (Danny)
- [x] o1-labs/proof-systems#2249 (Danny)
- [x] o1-labs/proof-systems#2250 (Danny)
- [x] o1-labs/proof-systems#2243 (Fabrizio)
- [ ] o1-labs/proof-systems#2088 (Misha)
- [ ] https://github.com/o1-labs/proof-systems/pull/2270 (Deduplicating the folding environment, Fabrizio)
- [x] https://github.com/o1-labs/proof-systems/issues/2231 (Misha)

Confidence level: H

**Comment by joseandro** [comment]
PRs:
https://github.com/o1-labs/proof-systems/pull/2232
