### ISSUE TITLE
Finish implementing trust system

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#1733]
The initial code went in in #1570 and #1650, but it's not actually used anywhere. I don't want this work to be forgotten. We need to:
- [x] Replace all calls to `Banlist` code with trust system
- [x] Delete banlist library
- [x] Deprecate `Logger.faulty_peer`
- [x] Disconnect from currently connected peers proactively when they're banned (reading from ban pipe), track currently open connections in order to do so
- [x] ~reuse currently open connections while we're in there~ do this in #1859 instead
- [ ] implement all the TODO punishes
- [x] replace all calls to `Logger.faulty_peer` with punishments
- [x]  in catchup (#1426)
- [x] in syncable ledger (#435)
- [x] in transaction pool #1734
- [x] in bootstrap
- [x] in coda_networking
- [x] in ledger catchup
- [x] in gossip_net (especially check `try_call_rpc`)
- [x] in parallel scan
- [x] in staged ledger
- [x] in transition processor
- [ ] record `Fulfilled_request` in appropriate places: catchup, epoch ledger sync, ~syncable ledger~, etc
- [ ] record `Made_request` in those same places
- [ ] Deal with misbehavior inside the RPC layer e.g. if they send garbage during handshaking or send queries/responses that don't check. EDIT: I think it'll be sufficient to pass the right thing in the `on_handshake_error` parameter of `server_with_close` and handle error results when we make requests. But double check.
- [ ] Audit code for things that should be punishable but don't call `Logger.faulty_peer` or have a `TODO: punish` comment
- [ ] Figure out if we should / how to punish peers for being slow. [Slowloris](https://en.wikipedia.org/wiki/Slowloris_(computer_security))-style attacks are a concern.
- [x] Prevent multiple inbound connections from the same IP. If for some reason we decide not to do this, we still need to modify the hashtable code mapping ips to connections in `gossip_net.ml` to close all connections from a given IP when the IP is banned. In progress in #2067
- [ ] **Test this stuff somehow.**

**Comment by enolan** [comment]
Here's an example from syncable ledger, for illustration:

```ocaml
        let%bind _ =
          match (query, answer) with
          | Query.What_child_hashes addr, Answer.Child_hashes_are (lh, rh) -> (
            match add_child_hashes_to t addr lh rh with
            | `Hash_mismatch (expected, actual) ->
                let%map () =
                  record_envelope_sender t.trust_system t.logger sender
                    ( Actions.Sent_bad_hash
                    , Some
                        ( "sent child hashes $lhash and $rhash for address \
                           $addr, they merge hash to $actualmerge but we \
                           expected $expectedmerge"
                        , [ ("lhash", Hash.to_yojson lh)
                          ; ("rhash", Hash.to_yojson rh)
                          ; ("actualmerge", Hash.to_yojson actual)
                          ; ("expectedmerge", Hash.to_yojson expected) ] ) )
                in
                requeue_query ()
            | `Good children_to_verify ->
                (* TODO #312: Make sure we don't write too much *)
                List.iter children_to_verify ~f:(fun (addr, hash) ->
                    handle_node t addr hash ) ;
                record_envelope_sender t.trust_system t.logger sender
                  ( Actions.Fulfilled_request
                  , Some
                      ( "sync ledger query $query"
                      , [("query", Query.to_yojson Addr.to_yojson query)] ) ) )

```
In words, if `add_child_hashes` returns `` `Hash_mismatch``, that indicates the peer lied. We call `record_envelope_sender`, passing the trust system, the logger and the sender from the envelope, along with a tuple of the `Sent_bad_hash` action and an optional fancy log message. Then we requeue the query, so we can get a result from an honest peer. If it returns `` `Good``, that indicates the hash value was correct. We call `record_envelope_sender` with the `Fulfilled_request` action to reward them.

General algorithm for updating code to use the trust system:
* For every place where a peer can consume resources, misbehave or be helpful:
  * Figure out who to blame. If you already have an envelope you can use `record_envelope_sender`, if you have an IP you can use `record` directly. If you have neither you'll have to thread that information in or handle trust actions in a caller.
  * Figure out which member of `Trust_system.Action.t` is appropriate, or, if none are, add a new one.
  * Call the appropriate record function.
  * If misbehavior means we didn't get data we wanted or we didn't send message we needed to send, queue a retry attempt.

**Comment by enolan** [comment]
Went through and checked the boxes for stuff that is done now.
