### ISSUE TITLE
Gossip Traffic Analysis

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4721]
Produce the following tools for use in debugging Coda Testnets: 
- [x] Address inconsistencies between GraphQL block representation and Logs [#4810]
- [x] Add receiver field to metadata for received block logs [#4816]
- [x] Lay the framework for a CLI tool which functionality can be added to [#4731]
- [x] Tool to determine if network is partitioned from block gossip logs [#4732]
- [ ] Tool to determine severity and magnitude of a fork from block gossip logs [#4733]

Exit Criteria
- Interfaces for this work are clearly defined
- Interfaces are consistent (i.e. log formatting) such that they facilitate analysis
- Basic tools written allowing manual review of network state

**Comment by aneesharaines** [comment]
@yourbuddyconner - can you add the exit criteria to the description?
