### ISSUE TITLE
Key Management & Runtime Ledger

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4722]
Goal: 

Produce tooling around creation and lifecycle management of "keysets"

Action Items: 
- [x] Write an RFC for the Design of the tool [#4728]
- [x] Build a tool with which a set of private/public key pairs can be generated and stored 
- [x] Build a tool with which a set of private/public keys can be loaded and injected into a k8s namespace as secrets [#4729]
- [ ] Build a tool with which a set of stored public keys can be converted to a Genesis Ledger and injected into a k8s namespace as a ConfigMap [#4730]

Exit Criteria: 
1. It's possible to generate a set of new keypairs for inclusion in a network in one command.
2. It's possible to generate a genesis ledger based on the new keypairs in one command.
3. These keypairs and ledger can be injected into a kubernetes environment for testing.

**Comment by aneesharaines** [comment]
Do we need to build something here or are there existing solutions we can use that we can just integrate?

**Comment by aneesharaines** [comment]
Should there be an exit criteria around how this fits into QA net deployments?  Or is that covered by exit criteria #3?

**Comment by aneesharaines** [comment]
Need to revisit on what changes need to be done to incorporate the keyset too more fulling into the deployment
