### ISSUE TITLE
Testnet Deployment Environment

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4723]
Goal: 

To have a system for deploying Testnets that covers the complete lifecycle of integration testing, manual QA, and public deployment. 

Action Items: 
- [x] Include Faucet Bot in deployment
- [x] Include Archive Node in deployment
- [ ] Include Testnet Points Job in deployment
- [x] Include Block Producers in deployment (including keys)
- [x] Include independently scalable SNARK Coordinator/Workers
- [x] Allow Testnet to be deployed with a runtime Genesis Timestamp 
- [x] Allow Testnet to be deployed with a runtime Genesis Ledger [#4782]
- [x] Allow for incremental Product Deployments (Bots and Services) 
Exit Criteria
- Public Testnet deployable with all required features present
- QA Testnet has all interfaces implemented and ability to deploy on a schedule
-  . >50% of protocol team and >50% of product team has successfully deployed QA-net-infrastructure without help
- Solution for sharing keys (covered in #4722 )
-  Configuration of networks requires minimal knowledge of infra code -- at the most requiring just 1 or 2 top-level files being touched (covered in #4723)
- Minimal config.mlhs, all unnecessary ones removed, files named properly (covered in #4756)

**Comment by aneesharaines** [comment]
@yourbuddyconner - can you add the exit criteria to the description?

**Comment by aneesharaines** [comment]
~ 2 weeks remaining
