### ISSUE TITLE
Open Tracing Infrastructure 

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4726]
- [ ] Deploy Jaeger via Helm Chart
- [ ] Deploy PoC Open Tracing App 
- [ ] Instrument Coda Daemon w/ Open Tracing

**Comment by aneesharaines** [comment]
@yourbuddyconner - can you add the exit criteria to the description?
