### ISSUE TITLE
Integration Testing Framework + Infrastructure

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4735]
Adopting some version of https://github.com/CodaProtocol/coda/pull/4715

Friction points:
  - Tests are not abstract over the execution environment (local and on a network with multiple nodes)
      - Many tests and benchmarks are blocked on multiple nodes testing
  - Tests are tightly coupled to build profiles — this is addressed by build constants
  - Tests are too difficult to debug
      - Local process test harness contains boilerplate assumptions and assertions across all tests; all tests too extreme
      - We don't have much information as to what a test is doing when the test fails. We don't have a good way to surface logs+metrics and collect them. Logs are squished in a way that's hard to deal with
      - Timeouts in tests result in immediate cancellation of tests. Failures are triggered by slight performance regressions (soft timeouts)
  - Tests require too much internal knowledge to write. Tests should be accessible to all the protocol engineers, product engineers, infrastructure engineers.
  - We can't write integration tests that are "true" integration (x-cli, graphql, product, infrastructure)

To flesh out into further issues:

- [x] Specify plan for structure logs (#4759)
- [x] Specify infrastructure plan for integration test framework (#4917)
- [x] Port and add structured event logs (#5102)
- [x] Implement coda-automation deployments from OCaml (#4767)
- [x] Implement StackDriver interface (#5103)
- [x] Implement puppeteered container image
- [x] Combine interfaces and create functor inputs for test descriptions (#5380)
- [x] Implement communication to puppeteer process (#5385)
- [x] Implement monad (#5366)
- [x] Create transaction test (#5381)
- [x] Convert bootstrap test (#4765)

Exit criteria:

1. We have at least 1 test that covers one of the 3.2 bootstrap/catchup issues (entails remote execution)
2. Port at least 1 existing test over to this framework
3. (Speed) We don't need a separate build per test
4. (Debugability) All log data is retrievable across all the nodes -> and tagged by node
5. Enable "true" integration with a proof-of-concept -- GraphQL schema checker test (requires a running daemon to test properly)
6. Possible to iterate fixes on one test (you can run it without having to wait for entire CI pipeline)
7. There is a DSL (https://github.com/MinaProtocol/mina/blob/rfc/integration-tests/docs/test_dsl_spec.md) that makes it easy for folks to write tests even if they aren't super familiar with OCaml
    * Document the tests in a way that can be understood by folks unfamiliar with our codebase

**Comment by nholland94** [comment]
Here is a dependency graph I put together for some of the upcoming work that is necessary before we can begin working on the actual integration testing framework. Blue represents what is currently in progress, green represents what is completed as of now.

![int-test dot](https://user-images.githubusercontent.com/5352803/82369216-8959dc80-99cb-11ea-8c56-8b0215247e2e.png)
