### ISSUE TITLE
[RFC] Local Network Testing Framework

### ISSUE THREAD

**Issue by figitaki** [MinaProtocol/mina#7332]
There are a few ways to test changes to the protocol or associated API's. This proposal focuses on integration testing the overall protocol and peripheral tools. The core of the testing will be a local network generated using the `run_local_network.sh` script, which will then be tested through the GraphQL APIs. Additionally if this tool is written in Rescript targeting the Nodejs environment, we can easily extend it to test the Client SDK and Testnet SDKs.

## Use Cases

- Testing the core functionality of the protocol (i.e. block/snark production, consensus, networking etc.)
- Testing the end-to-end flows of using the GraphQL APIs to interact with a network
- Compatibility of the Testnet SDK, Client SDK, and GraphQL APIs

## Example Test Case

Here's a very basic example that will most likely serve as the first real test implemented by this tool:

1. Spin up a local network
2. Send transactions to the network until the staged ledger is emitted
3. Validate the state in the ledger

Since this tool will need to run in Buildkite, we will need to move the `run_local_network.sh` script into Docker. Next, we can utilize the GraphQL APIs of the node to send transactions until the staged ledger emits. We can subscribe to the `blocks` query to follow the ledger as blocks are produced.

## Phases

In order to get to a minimum viable product as quickly as possible, here's an incremental approach that breaks the functionality into three phases:

1. Core protocol functionality (~1 wk)
2. GraphQL API coverage (~1 wk)
3. Client SDK and Testnet SDK compatibility (~3 days)

These estimates do not consider the additional work that could be uncovered from testing.

## Tasks

- [x] Docerify the `run-local-network.sh` script 
- [x] **Blocker** Add a boolean for when the staged ledger emits to the GraphQL API #75978
- [ ] **Blocker** Generate a `DEBUG` build in docker [related PR](https://github.com/MinaProtocol/mina/pull/7323)
- [ ] Write a simple testing service in ReasonML that uses the GraphQL endpoints of a node to generating transactions to the point of emitting the staged ledger #7597
